### ISSUE TITLE
DEBUG should not be True

### ISSUE THREAD

**Issue by mahmoudhossam** [transportforcairo/Metro-GTFS#1]
Going to http://otp.transportforcairo.com/ currently shows this ![alttext](http://i.imgur.com/h3QZBgE.png)

Setting `DEBUG = False` should prevent this from happening.

**Comment by transportforcairo** [comment]
@mahmoudhossam 

Hi Mahmoud,
You are receiving this bug as we have shut down the server in question.
Do you have any particular interest in accessing it?
